### ISSUE TITLE
看到您4天前新做了update,我想使用播放界面，布局及动画效果，请问当前是否存在问题

### ISSUE THREAD

**Issue by Zhangxd77** [GiitSmile/ImitateNetEasyCloud#3]

**Comment by Litten1106** [comment]
啊哈，没想到还有人关注到这个项目，这个项目是两年前工作间隙做的，当时停止更新也是因为事情过多了，最近更新是因为我更新了AS到3.0顺带更新了gradle文件，之前是适配的Android6.0版本吧然后界面上应该是没有太大的问题的，只是可能要针对7.0做些额外的处理了
